name: OneActionTp
version: @version@
main: click.seichi.oneactiontp.OneActionTp

commands:
  tpp:
    usage: /tpp <playername>
    permission: oneactiontp.tpp
    description: This command allows players to send a teleport request.
  tppdeny:
    usage: /tppdeny <playername>
    permission: oneactiontp.tppdeny
    description: This command allows players to deny the teleport request.
  tpptoggle:
    usage: /tpptoggle
    permission: oneactiontp.tpptoggle
    description: This command allows players to toggle either they accept or deny all requests automatically.