name: OneActionTp
version: @version@
main: click.seichi.oneactiontp.OneActionTp

commands:
  tpt:
    usage: /tpt <playername>
    aliases: tpthere
    permission: oneactiontp.tpt
    description: This command allows players to send a teleport request.
  tph:
    usage: /tph <playername>
    aliases: tphere
    permission: oneactiontp.tph
    description: This command allows players to send a teleport request.
  tpaccept:
    usage: /tpaccept <playername>
    permission: oneactiontp.tpdeny
    description: This command allows players to accept the teleport request.
  tpdeny:
    usage: /tpdeny <playername>
    permission: oneactiontp.tpdeny
    description: This command allows players to deny the teleport request.
  tpcancel:
    usage: /tpcancel <playername>
    permission: oneactiontp.tpcancel
    description: This command allows players to cancel the teleport request.
  tptoggle:
    usage: /tptoggle
    permission: oneactiontp.tptoggle
    description: This command allows players to toggle either they accept or deny all requests automatically.